import { useGLTF } from "@react-three/drei";
import { useMediaQuery } from "react-responsive";

export function Room(props) {
  const { nodes, materials } = useGLTF("/models/optimized-room.glb");
  const isMobile = useMediaQuery({ query: "(max-width: 768px)" });

  return (
    <group {...props} dispose={null} scale={isMobile ? 0.8 : 1}>
      {nodes.pCube6_blinn1_0?.geometry && (
        <mesh
          geometry={nodes.pCube6_blinn1_0.geometry}
          material={materials.blinn1}
          castShadow={!isMobile}
          receiveShadow={!isMobile}
        />
      )}

      <mesh
        geometry={nodes.body1_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.cabin_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.chair_body_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.comp_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.emis_lambert1_0.geometry}
        material={materials.lambert1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.handls_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.keyboard_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.kovrik_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.lamp_bl_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.lamp_white_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.miuse_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.monitor2_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.monitor3_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.pCylinder5_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.pillows_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.polySurface53_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0001.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.railing_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.red_bttns_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.red_vac_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.stylus_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.table_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.tablet_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.triangle_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.vac_black_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.vacuum1_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.vacuumgrey_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.vires_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.window_blinn1_0.geometry}
        material={materials.blinn1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
      <mesh
        geometry={nodes.window4_phong1_0.geometry}
        material={materials.phong1}
        castShadow={!isMobile}
        receiveShadow={!isMobile}
      />
    </group>
  );
}

useGLTF.preload("/models/optimized-room.glb");
